#!/bin/bash

set -x

$PREFIX/snap/bin/snap --nosplash --nogui --modules --install org.esa.snap.idepix.core
$PREFIX/snap/bin/snap --nosplash --nogui --modules --install org.esa.snap.idepix.olci

( cmdpid=$BASHPID; (sleep 30; kill $cmdpid) & exec $PREFIX/snap/bin/snap --nosplash --nogui --modules --list --refresh )

$PREFIX/snap/bin/snap --nosplash --nogui --modules --update org.esa.s3tbx.s3tbx.rad2refl

( cmdpid=$BASHPID; (sleep 30; kill $cmdpid) & exec $PREFIX/snap/bin/snap --nosplash --nogui --modules --list --refresh )

export GPT_BIN=$PREFIX/snap/bin/gpt

/opt/anaconda/envs/env_s3/bin/stage-in -c .binder/stage-in.yml -t /workspace/data/

exit 0
