#!/bin/bash

# theia
. "$NVM_DIR/nvm.sh"	

if [[ ! -L /workspace/package.json  ]]; then
  ln -s /srv/theia/package.json /workspace/package.json
fi

if [[ ! -L /srv/theia/src-gen ]]; then
  ln -s /srv/theia/src-gen /workspace/src-gen
fi

if [[ ! -d /workspace/.theia ]]; then
  mkdir /workspace/.theia
fi

if [[ ! -L /home/jovyan/.theia  ]]; then
  ln -s /workspace/.theia  /home/jovyan/.theia
fi

export PATH=/srv/theia/node_modules/@theia/cli/bin:${PATH}

# snap 
export PATH=/srv/conda/envs/notebook/snap/bin:${PATH}

exec "$@" 